apiVersion: apps/v1
kind: Deployment
metadata:
name: wordpress-green
spec:
replicas: 2
selector:
matchLabels:
app: wp
version: green
template:
metadata:
labels:
app: wp
version: green
spec:
containers:
- name: wp
image: <ECR-URI>:green
ports:
- containerPort: 80
