apiVersion: apps/v1
kind: Deployment
metadata:
name: wordpress-blue
spec:
replicas: 2
selector:
matchLabels:
app: wp
version: blue
template:
metadata:
labels:
app: wp
version: blue
spec:
containers:
- name: wp
image: <ECR-URI>:blue
ports:
- containerPort: 80
